// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM65IhbmB7bhD4YKgPUsK58rqtCar1PeE',
    appId: '1:846887607030:web:319cde79b97f0bcb206ad7',
    messagingSenderId: '846887607030',
    projectId: 'shop-ed9f1',
    authDomain: 'shop-ed9f1.firebaseapp.com',
    storageBucket: 'shop-ed9f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1-ULmc2Z7_7Ve4A_uVGx1dwdc2lZtbUc',
    appId: '1:846887607030:android:6134554d4a3c997c206ad7',
    messagingSenderId: '846887607030',
    projectId: 'shop-ed9f1',
    storageBucket: 'shop-ed9f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtUt-OKW4Cx2kf2hB7iomBEVYJODSF1yU',
    appId: '1:846887607030:ios:141c04cca3c18d97206ad7',
    messagingSenderId: '846887607030',
    projectId: 'shop-ed9f1',
    storageBucket: 'shop-ed9f1.firebasestorage.app',
    iosBundleId: 'com.sinasys.eCommerceFlutter',
  );
}
