// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6jQ03fUxOCfY-tgpEsynj67UK6boiMw',
    appId: '1:714509820044:web:a00e6d3c81ec28a27d9ba9',
    messagingSenderId: '714509820044',
    projectId: 'shop-60346',
    authDomain: 'shop-60346.firebaseapp.com',
    storageBucket: 'shop-60346.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUehrrnGXap6UPe4romwBpvKAWOxWDQBk',
    appId: '1:714509820044:android:e77855655792aacd7d9ba9',
    messagingSenderId: '714509820044',
    projectId: 'shop-60346',
    storageBucket: 'shop-60346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATX7zo9oGsU6iPfm5iw9_sV_mBmN5gY1o',
    appId: '1:714509820044:ios:5e8b03033a9c3ceb7d9ba9',
    messagingSenderId: '714509820044',
    projectId: 'shop-60346',
    storageBucket: 'shop-60346.firebasestorage.app',
    iosBundleId: 'com.sinasys.eCommerceFlutter',
  );
}
